/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shapetotable.view;

import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import shapetotable.dao.CadastroDiretorioDao;
import shapetotable.database.ConnectionDBH2;
import shapetotable.domain.CadastroDiretorio;

/**
 *
 * @author Guilherme
 */
public class CadastroDiretorioView extends javax.swing.JFrame {

    public void ListarJTable() {
        try {

            CadastroDiretorioDao buscarCadastros = new CadastroDiretorioDao();

            jTblDiretorio.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTblDiretorio.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTblDiretorio.getColumnModel().getColumn(2).setPreferredWidth(500);
            DefaultTableModel tabela = (DefaultTableModel) jTblDiretorio.getModel();

            tabela.setNumRows(0);

            for (CadastroDiretorio listar : buscarCadastros.getListarCadDir()) {
                //            System.out.println("ID: " + listar.getIdCaminho());
                tabela.addRow(new Object[]{
                    listar.getIdCaminho(),
                    listar.getDescricao(),
                    listar.getCaminhoShape()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema ao listar: " + e.getMessage());
        }

    }

    /**
     * Creates new form CadastroDiretorioView
     */
    public CadastroDiretorioView() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblDiretorio = new javax.swing.JTable();
        jBtnExcluir = new javax.swing.JButton();
        jTxDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxCaminho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnProcurar = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnConcluir = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Diretório (Shape)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frmCadastroDiretorio"); // NOI18N
        setPreferredSize(new java.awt.Dimension(690, 308));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTblDiretorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIÇÃO", "CAMINHO (Shape)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblDiretorio.getTableHeader().setReorderingAllowed(false);
        jTblDiretorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblDiretorioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblDiretorio);

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jTxDescricao.setName(""); // NOI18N

        jLabel1.setText("DESCRIÇÃO");

        jLabel2.setText("CAMINHO (Shape)");

        jBtnProcurar.setText("Procurar...");
        jBtnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProcurarActionPerformed(evt);
            }
        });

        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnConcluir.setText("Cadastrar");
        jBtnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConcluirActionPerformed(evt);
            }
        });

        jBtnLimpar.setText("Limpar Campos");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxCaminho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnProcurar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnProcurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConcluir)
                    .addComponent(jBtnLimpar))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        
        if (jTblDiretorio.getSelectedRow() > -1) {

            if (JOptionPane.showConfirmDialog(null, "Realmente deseja Remover o registro selecionado?", "Remoção de Registro", JOptionPane.OK_CANCEL_OPTION,0,new ImageIcon("./Src/Icones/interrogacao.png")) == 0) {

                int linhaSelecionada = jTblDiretorio.getSelectedRow();
                CadastroDiretorio remove = new CadastroDiretorio();

                remove.setIdCaminho((int) jTblDiretorio.getValueAt(linhaSelecionada, 0));

                CadastroDiretorioDao removerDiretorioDao = new CadastroDiretorioDao();
                removerDiretorioDao.removerCadDir(remove);

                this.ListarJTable();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Atenção: para remover algum registro é necessário selecionar alguma linha.",
                    "Alteração de Registro", JOptionPane.PLAIN_MESSAGE);
        }

        jTxDescricao.setText("");
        jTxCaminho.setText("");
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed

        if ((!jTxDescricao.getText().isEmpty()) && (!jTxCaminho.getText().isEmpty())) {
        //Icon figura = new ImageIcon();
            if (JOptionPane.showConfirmDialog(null, "Realmente deseja Alterar o registro selecionado?", "Alteração de Registro", JOptionPane.OK_CANCEL_OPTION,0,new ImageIcon("./Src/Icones/interrogacao.png")) == 0) {

                int linhaSelecionada = jTblDiretorio.getSelectedRow();
                CadastroDiretorio altera = new CadastroDiretorio();

                altera.setDescricao(jTxDescricao.getText());
                altera.setCaminhoShape(jTxCaminho.getText());
                altera.setIdCaminho((int) jTblDiretorio.getValueAt(linhaSelecionada, 0));

                CadastroDiretorioDao alterarDiretorioDao = new CadastroDiretorioDao();
                alterarDiretorioDao.atualizarCadDir(altera);

                this.ListarJTable();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Atenção: para alterar algum registro é necessário selecionar alguma linha.\nDepois de alterar a Descrição ou o Caminho, clique em Alterar.",
                    "Alteração de Registro", JOptionPane.PLAIN_MESSAGE);
        }

        jTxDescricao.setText("");
        jTxCaminho.setText("");

    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //Popular os dados cadastrados na tabela
        this.ListarJTable();

    }//GEN-LAST:event_formWindowOpened

    private void jBtnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConcluirActionPerformed
        if (jTblDiretorio.getSelectedRow() == -1) {
            if ((!jTxDescricao.getText().isEmpty()) && (!jTxCaminho.getText().isEmpty())) {
                CadastroDiretorio novo = new CadastroDiretorio();
                novo.setDescricao(jTxDescricao.getText());
                novo.setCaminhoShape(jTxCaminho.getText());

                CadastroDiretorioDao cadastrarDiretorioDao = new CadastroDiretorioDao();
                cadastrarDiretorioDao.inserirCadDir(novo);

                this.ListarJTable();

                jTxDescricao.setText("");
                jTxCaminho.setText("");
                //jBtnProcurar.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(null, "Falta incluir a Descrição ou o Caminho!\nFavor revisar os campos antes de Cadastrar.",
                        "Novo Registro", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Impossível cadastrar, pois este registro já existe!\nLimpe os campos e preencha corretamente antes de cadastrar!.",
                        "Novo Registro", JOptionPane.PLAIN_MESSAGE);
        }

    }//GEN-LAST:event_jBtnConcluirActionPerformed

    private void jBtnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProcurarActionPerformed

        JFileChooser arquivo = new JFileChooser();
        arquivo.setFileFilter(new FileNameExtensionFilter("Arquivo Shape (.shp)", "shp"));
        arquivo.setAcceptAllFileFilterUsed(false);

        if (arquivo.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File arquivoNome = arquivo.getSelectedFile();

        jTxCaminho.setText(arquivoNome.getPath());
        //System.out.println("Caminho: " + arquivoNome.getPath());

    }//GEN-LAST:event_jBtnProcurarActionPerformed

    private void jTblDiretorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblDiretorioMouseClicked

        // Preencher campos de Descrição e Caminho ao clicar em alguma linha da tabela
        int linhaSelecionada = jTblDiretorio.getSelectedRow();
        jTxDescricao.setText((String) jTblDiretorio.getValueAt(linhaSelecionada, 1));
        jTxCaminho.setText((String) jTblDiretorio.getValueAt(linhaSelecionada, 2));

        jTxDescricao.setEditable(true);
        jTxCaminho.setEditable(true);
        jBtnProcurar.setEnabled(true);

    }//GEN-LAST:event_jTblDiretorioMouseClicked

    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed

        jTxDescricao.setText("");
        jTxCaminho.setText("");
        jTblDiretorio.clearSelection();

    }//GEN-LAST:event_jBtnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDiretorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDiretorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDiretorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDiretorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDiretorioView().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Sol.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnConcluir;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnProcurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblDiretorio;
    private javax.swing.JTextField jTxCaminho;
    private javax.swing.JTextField jTxDescricao;
    // End of variables declaration//GEN-END:variables
}
