/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shapetotable.view;

import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import shapetotable.dao.CadastroBancoDao;
import shapetotable.database.ConnectionDBOracle;
import shapetotable.database.ConnectionDBOracleBoneCP;
import shapetotable.domain.CadastroBanco;

/**
 *
 * @author Guilherme
 */
public class CadastroBancoView extends javax.swing.JFrame {

    private int SELECAO_COMUM_TNS = 0; // Quando for 1 = Comum, se for 2 = TNS

    public void controlarJRadioButtons(JRadioButton rBselecionado) { //METODO PARA CONTROLAR A ALTERNANCIA DOS JRadioButtons

        if (rBselecionado.isSelected()) {
            String selecionado = rBselecionado.getActionCommand();
            if (selecionado.contentEquals("COMUM")) {
                SELECAO_COMUM_TNS = 1;
                jRbTns.setSelected(false);
                jTaTns.setEnabled(false);
                jTxHost.setEnabled(true);
                jTxSid.setEnabled(true);
                jTxPorta.setEnabled(true);
                jTxHost.grabFocus();
            }
            if (selecionado.contentEquals("TNS")) {
                SELECAO_COMUM_TNS = 2;
                jRbComum.setSelected(false);
                jTaTns.setEnabled(true);
                jTaTns.setEditable(true);
                jTxHost.setEnabled(false);
                jTxSid.setEnabled(false);
                jTxPorta.setEnabled(false);
                jTaTns.grabFocus();
            }
            //System.out.println("SELECAO_COMUM_TNS: " + SELECAO_COMUM_TNS);
        }
    }

    public void ListarJTable() { //METODO PARA TRAZER OS DADOS PARA A TABELA
        try {

            CadastroBancoDao buscarCadastros = new CadastroBancoDao();

            jTblBanco.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTblBanco.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTblBanco.getColumnModel().getColumn(2).setPreferredWidth(160);
            DefaultTableModel tabela = (DefaultTableModel) jTblBanco.getModel();

            tabela.setNumRows(0);

            buscarCadastros.getListarCadBanco().forEach((listar) -> { //percorre o retorno do objeto arraylist
                tabela.addRow(new Object[]{
                    listar.getIdBanco(),
                    listar.getNomeConexao(),
                    listar.getUsuario()
                });
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema ao listar: " + e.getMessage());
        }
    }

    /**
     * Creates new form CadastroDiretorioView
     */
    public CadastroBancoView() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblBanco = new javax.swing.JTable();
        jBtnExcluir = new javax.swing.JButton();
        jTxNomeConexao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBtnAlterar = new javax.swing.JButton();
        jBtnConcluir = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRbComum = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTxHost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxSid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxPorta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRbTns = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaTns = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTxUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxSenha = new javax.swing.JPasswordField();
        jBtnTestar = new javax.swing.JButton();
        jCBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Banco (Oracle)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frmCadastroDiretorio"); // NOI18N
        setPreferredSize(new java.awt.Dimension(518, 638));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTblBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME CONEXÃO", "USUÁRIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblBanco.getTableHeader().setReorderingAllowed(false);
        jTblBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblBancoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblBanco);

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setMaximumSize(new java.awt.Dimension(90, 41));
        jBtnExcluir.setMinimumSize(new java.awt.Dimension(90, 41));
        jBtnExcluir.setPreferredSize(new java.awt.Dimension(90, 41));
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jTxNomeConexao.setName(""); // NOI18N

        jLabel1.setText("NOME DA CONEXÃO");

        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setMaximumSize(new java.awt.Dimension(90, 41));
        jBtnAlterar.setMinimumSize(new java.awt.Dimension(90, 41));
        jBtnAlterar.setPreferredSize(new java.awt.Dimension(90, 41));
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnConcluir.setText("Cadastrar");
        jBtnConcluir.setMaximumSize(new java.awt.Dimension(90, 41));
        jBtnConcluir.setMinimumSize(new java.awt.Dimension(90, 41));
        jBtnConcluir.setPreferredSize(new java.awt.Dimension(90, 41));
        jBtnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConcluirActionPerformed(evt);
            }
        });

        jBtnLimpar.setText("<html>\n<center>Limpar \n<p>Campos");
        jBtnLimpar.setMaximumSize(new java.awt.Dimension(90, 41));
        jBtnLimpar.setMinimumSize(new java.awt.Dimension(90, 41));
        jBtnLimpar.setPreferredSize(new java.awt.Dimension(90, 41));
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRbComum.setText("COMUM");
        jRbComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbComumActionPerformed(evt);
            }
        });

        jLabel4.setText("HOST (ou IP)");

        jLabel5.setText("SID");

        jLabel6.setText("PORTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRbComum))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTxHost, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxSid, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTxPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRbComum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(53, 53, 53))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRbTns.setText("TNS");
        jRbTns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbTnsActionPerformed(evt);
            }
        });

        jTaTns.setColumns(20);
        jTaTns.setRows(5);
        jScrollPane2.setViewportView(jTaTns);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRbTns)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRbTns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
        );

        jLabel2.setText("USUÁRIO");

        jTxUsuario.setName(""); // NOI18N

        jLabel3.setText("SENHA");

        jBtnTestar.setText("<html>\n<center>Testar \n<p>Conexão");
        jBtnTestar.setMaximumSize(new java.awt.Dimension(90, 41));
        jBtnTestar.setMinimumSize(new java.awt.Dimension(90, 41));
        jBtnTestar.setPreferredSize(new java.awt.Dimension(90, 41));
        jBtnTestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTestarActionPerformed(evt);
            }
        });

        jCBox.setText("Mostrar");
        jCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnTestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxNomeConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCBox))
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxNomeConexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCBox)
                    .addComponent(jTxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBtnTestar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBtnLimpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnConcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed

        if (jTblBanco.getSelectedRow() > -1) {

            if (JOptionPane.showConfirmDialog(null, "Realmente deseja Remover o registro selecionado?", "Remoção de Registro", JOptionPane.OK_CANCEL_OPTION,0,new ImageIcon("./Src/Icones/interrogacao.png")) == 0) {

                int linhaSelecionada = jTblBanco.getSelectedRow();
                CadastroBanco remove = new CadastroBanco();

                remove.setIdBanco((int) jTblBanco.getValueAt(linhaSelecionada, 0));

                CadastroBancoDao removerDiretorioDao = new CadastroBancoDao();
                removerDiretorioDao.removerCadBanco(remove);

                this.ListarJTable();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Atenção: para remover um registro é necessário selecionar alguma linha.",
                    "Alteração de Registro", JOptionPane.PLAIN_MESSAGE);
        }
//
//        jTxNomeConexao.setText("");
//        jTxCaminho.setText("");
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed

        if ((!jTxNomeConexao.getText().isEmpty()) && (!jTxUsuario.getText().isEmpty()) && (!jTxSenha.getText().isEmpty())) {

            int linhaSelecionada = jTblBanco.getSelectedRow();
            CadastroBanco altera = new CadastroBanco();

            altera.setNomeConexao(jTxNomeConexao.getText());
            altera.setUsuario(jTxUsuario.getText());
            altera.setSenha(new String(jTxSenha.getPassword()).trim());

            if (SELECAO_COMUM_TNS == 1) { //ALTERA REGISTRO DE CONEXÃO COMUM 
                //System.out.println("SELECAO COMUM ou TNS: " + SELECAO_COMUM_TNS);
                if ((!jTxHost.getText().isEmpty()) && (!jTxSid.getText().isEmpty()) && (!jTxPorta.getText().isEmpty())) {
                    if (JOptionPane.showConfirmDialog(null, "Realmente deseja Alterar o registro selecionado?", "Alteração de Registro", JOptionPane.OK_CANCEL_OPTION,0,new ImageIcon("./Src/Icones/interrogacao.png")) == 0) {

                        altera.setHost(jTxHost.getText());
                        altera.setSid(jTxSid.getText().toUpperCase());
                        try {
                            altera.setPorta(Integer.valueOf(jTxPorta.getText()));
                            altera.setIdBanco((int) jTblBanco.getValueAt(linhaSelecionada, 0));
                            CadastroBancoDao alterarBancoDao = new CadastroBancoDao();
                            alterarBancoDao.atualizarCadBancoComum(altera);
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "O campo PORTA suporta apenas o uso de números!",
                                    "Novo Registro", JOptionPane.PLAIN_MESSAGE);
                        }

                        this.ListarJTable();
                        jBtnLimparActionPerformed(evt);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Impossível alterar o cadastro sem incluir: Host, SID e Porta.",
                            "Alteração de Registro", JOptionPane.PLAIN_MESSAGE);
                }
            } else if (SELECAO_COMUM_TNS == 2) { //ALTERA REGISTRO DE CONEXÃO TNS
                if ((!jTaTns.getText().isEmpty())) {
                    if (JOptionPane.showConfirmDialog(null, "Realmente deseja Alterar o registro selecionado?", "Alteração de Registro", JOptionPane.OK_CANCEL_OPTION,0,new ImageIcon("./Src/Icones/interrogacao.png")) == 0) {

                        altera.setTNS(jTaTns.getText());
                        altera.setIdBanco((int) jTblBanco.getValueAt(linhaSelecionada, 0));

                        CadastroBancoDao alterarBancoDao = new CadastroBancoDao();
                        alterarBancoDao.atualizarCadBancoTNS(altera);

                        this.ListarJTable();
                        jBtnLimparActionPerformed(evt);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Impossível alterar o cadastro sem incluir: TNS.",
                            "Alteração de Registro", JOptionPane.PLAIN_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Atenção: para alterar algum registro é necessário selecionar alguma linha.\nDepois de alterar a Descrição ou o Caminho, clique em Alterar.",
                    "Alteração de Registro", JOptionPane.PLAIN_MESSAGE);
        }


    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //Popular os dados cadastrados na tabela
        this.ListarJTable();

    }//GEN-LAST:event_formWindowOpened

    private void jBtnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConcluirActionPerformed
        if (jTblBanco.getSelectedRow() == -1) {
            if ((!jTxNomeConexao.getText().isEmpty()) && (!jTxUsuario.getText().isEmpty()) && (!jTxSenha.getText().isEmpty())) {

                CadastroBanco novo = new CadastroBanco();
                novo.setNomeConexao(jTxNomeConexao.getText().trim());
                novo.setUsuario(jTxUsuario.getText().trim());
                novo.setSenha(new String(jTxSenha.getPassword()).trim());

                if (SELECAO_COMUM_TNS == 1) { // SE FOR COMUM
                    if ((!jTxHost.getText().isEmpty()) && (!jTxSid.getText().isEmpty()) && (!jTxPorta.getText().isEmpty())) {

                        novo.setHost(jTxHost.getText());
                        novo.setSid(jTxSid.getText().toUpperCase());
                        try {
                            novo.setPorta(Integer.valueOf(jTxPorta.getText()));
                            CadastroBancoDao cadastrarBancoDao = new CadastroBancoDao();
                            cadastrarBancoDao.inserirCadBancoComum(novo);
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "O campo PORTA suporta apenas o uso de números!",
                                    "Novo Registro", JOptionPane.PLAIN_MESSAGE);
                        }

                        this.ListarJTable();
                        jBtnLimparActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(null, "Impossível realizar o cadastro sem incluir: Host, SID e Porta.",
                                "Novo Registro", JOptionPane.PLAIN_MESSAGE);
                    }

                } else if (SELECAO_COMUM_TNS == 2) { // SE FOR TNS
                    if ((!jTaTns.getText().isEmpty())) {

                        novo.setTNS(jTaTns.getText().trim());

                        CadastroBancoDao cadastrarBancoDao = new CadastroBancoDao();
                        cadastrarBancoDao.inserirCadBancoTNS(novo);

                        this.ListarJTable();
                        jBtnLimparActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(null, "Impossível realizar o cadastro sem incluir: TNS.",
                                "Novo Registro", JOptionPane.PLAIN_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Falta incluir o Nome da Conexão, Usuário ou Senha!\nFavor revisar os campos antes de Cadastrar.",
                        "Novo Registro", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Impossível cadastrar, pois este registro já existe!\nLimpe os campos e preencha corretamente antes de cadastrar!.",
                    "Novo Registro", JOptionPane.PLAIN_MESSAGE);
        }

    }//GEN-LAST:event_jBtnConcluirActionPerformed

    private void jTblBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblBancoMouseClicked

        // Preencher campos de Descrição e Caminho ao clicar em alguma linha da tabela
        int linhaSelecionada = jTblBanco.getSelectedRow();
        int valorLinhaSelecionada = (int) jTblBanco.getValueAt(linhaSelecionada, 0);

        CadastroBancoDao buscarById = new CadastroBancoDao();
        String[] cadBancoLinha = new String[7];

        cadBancoLinha[0] = buscarById.getBuscarCadBanco(valorLinhaSelecionada).getNomeConexao();
        cadBancoLinha[1] = buscarById.getBuscarCadBanco(valorLinhaSelecionada).getUsuario();
        cadBancoLinha[2] = buscarById.getBuscarCadBanco(valorLinhaSelecionada).getSenha();
        cadBancoLinha[3] = buscarById.getBuscarCadBanco(valorLinhaSelecionada).getTNS();
        cadBancoLinha[4] = buscarById.getBuscarCadBanco(valorLinhaSelecionada).getHost();
        cadBancoLinha[5] = buscarById.getBuscarCadBanco(valorLinhaSelecionada).getSid();
        cadBancoLinha[6] = Integer.toString(buscarById.getBuscarCadBanco(valorLinhaSelecionada).getPorta());

        jTxNomeConexao.setText(cadBancoLinha[0]);
        jTxUsuario.setText(cadBancoLinha[1]);
        jTxSenha.setText(cadBancoLinha[2]);
        jTaTns.setText(cadBancoLinha[3]);
        jTxHost.setText(cadBancoLinha[4]);
        jTxSid.setText(cadBancoLinha[5]);
        if (cadBancoLinha[6].equals("0")) {
            jTxPorta.setText("");
        } else {
            jTxPorta.setText(cadBancoLinha[6]);
        }

        try {
            if (!cadBancoLinha[3].isEmpty()) { // Controlar RadioButton TNS
                jRbTns.setSelected(true);
                controlarJRadioButtons(jRbTns);
            }
        } catch (Exception e) {
            e.getMessage();
        }

        try {
            if (!cadBancoLinha[4].isEmpty()) { // Controlar RadioButton Comum
                jRbComum.setSelected(true);
                controlarJRadioButtons(jRbComum);
            }
        } catch (Exception e) {
            e.getMessage();
        }

        //jTxNomeConexao.setEditable(true);

    }//GEN-LAST:event_jTblBancoMouseClicked

    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed

        jTxNomeConexao.setText("");
        jTxUsuario.setText("");
        jTxSenha.setText("");
        jTxHost.setText("");
        jTxSid.setText("");
        jTxPorta.setText("");
        jTaTns.setText("");
        jTblBanco.clearSelection();
        jRbTns.setSelected(false);
        jRbComum.setSelected(false);
        jTxNomeConexao.grabFocus();

    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jRbComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbComumActionPerformed
        // TODO add your handling code here:
        this.controlarJRadioButtons(jRbComum);
    }//GEN-LAST:event_jRbComumActionPerformed

    private void jRbTnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbTnsActionPerformed
        // TODO add your handling code here:
        this.controlarJRadioButtons(jRbTns);
    }//GEN-LAST:event_jRbTnsActionPerformed

    private void jCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxActionPerformed
        // TODO add your handling code here:
        if (jCBox.isSelected()) {
            jTxSenha.setEchoChar('\u0000');
        } else {
            jTxSenha.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jCBoxActionPerformed

    private void jBtnTestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTestarActionPerformed

        if (jTblBanco.getSelectedRow() > -1) {

            int linhaSelecionada = jTblBanco.getSelectedRow();
            String usu;
            String sen;
            String tns;
            String host;
            String sid;
            int porta;

            CadastroBancoDao buscar = new CadastroBancoDao();
            CadastroBanco registroSelecionado;//= new CadastroBanco();

            registroSelecionado = buscar.getBuscarCadBanco((int) jTblBanco.getValueAt(linhaSelecionada, 0));
            usu = registroSelecionado.getUsuario();
            sen = registroSelecionado.getSenha();
            tns = registroSelecionado.getTNS();
            host = registroSelecionado.getHost();
            sid = registroSelecionado.getSid();
            porta = registroSelecionado.getPorta();

            ConnectionDBOracle conectar = new ConnectionDBOracle();
//              ConnectionDBOracleBoneCP conectar = new ConnectionDBOracleBoneCP();
            try {
                if (!tns.isEmpty()) { // Cria parametro de conexão Oracle com TNS
                    conectar.setParametrosConexaoTNS(tns, usu, sen);
                    //System.out.println("caiu no TNS");
                }
            } catch (Exception e) {
                //System.out.println("Erro: " + e.getMessage());
            }
            try {
                if (!host.isEmpty()) { // Cria parametro de conexão Oracle com Comum
                    //System.out.println("caiu no Comum");
                    conectar.setParametrosConexaoComum(host, sid, porta, usu, sen);
                }
            } catch (Exception e) {
                //System.out.println("Erro: " + e.getMessage());
            }

            try {
                Connection conectado = conectar.getConnection();
                if (!conectado.isClosed()) { //revisar este parametro de tempo em segundos
                    JOptionPane.showMessageDialog(null, "Conexão '"+ jTxNomeConexao.getText() + "' é Valida!", "Teste de Conexão", JOptionPane.PLAIN_MESSAGE);
                }
                conectar.closeAll(conectado);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Conexão '"+ jTxNomeConexao.getText() +"' Não é Valida!", "Teste de Conexão", JOptionPane.PLAIN_MESSAGE);
                //Logger.getLogger(CadastroBancoView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item da lista de Cadastros para testar a conexão!","Teste de Conexão",JOptionPane.PLAIN_MESSAGE);
        }


    }//GEN-LAST:event_jBtnTestarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroBancoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroBancoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroBancoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroBancoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroBancoView().setVisible(true);

            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Sol.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnConcluir;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnTestar;
    private javax.swing.JCheckBox jCBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRbComum;
    private javax.swing.JRadioButton jRbTns;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTaTns;
    private javax.swing.JTable jTblBanco;
    private javax.swing.JTextField jTxHost;
    private javax.swing.JTextField jTxNomeConexao;
    private javax.swing.JTextField jTxPorta;
    private javax.swing.JPasswordField jTxSenha;
    private javax.swing.JTextField jTxSid;
    private javax.swing.JTextField jTxUsuario;
    // End of variables declaration//GEN-END:variables
}
